USE DATABASE DATALAKE;
USE SCHEMA SOURCE_BAG;

-- Snowflake task to run the notebook + dbt project on a schedule.
-- Replace the placeholders below to match your DBT project location.
CREATE OR REPLACE TASK RUN_NOTEBOOK_SOURCE_BAG
  WAREHOUSE = CICD_WAREHOUSE
  SCHEDULE = 'USING CRON 0 6 * * * UTC'
  USER_TASK_TIMEOUT_MS = 14400000
  EXECUTE AS USER "CICD_USER_ROLE"
AS
  EXECUTE NOTEBOOK "SOURCE_BAG"."INGESTION_BAG";

CREATE OR REPLACE TASK RUN_DBT_PROJECT_SOURCE_BAG
  WAREHOUSE = CICD_WAREHOUSE
  AFTER RUN_NOTEBOOK_SOURCE_BAG
  USER_TASK_TIMEOUT_MS = 14400000
  EXECUTE AS USER "CICD_USER_ROLE"
AS
  EXECUTE DBT PROJECT "DATALAKE"."SOURCE_BAG"."SOURCE_BAG"
  ARGS = 'run';

ALTER TASK RUN_NOTEBOOK_SOURCE_BAG RESUME;
ALTER TASK RUN_DBT_PROJECT_SOURCE_BAG RESUME;
